name: Build GitHub Pages (Docs)

on:
  push:
      branches:
      - main
      paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install mkdocs-material
      - name: Build and Deploy MkDocs site
        run: mkdocs gh-deploy --force
