name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: "Python 3.9", python: "3.9-dev", os: "ubuntu"}
          - {name: "Python 3.10", python: "3.10-dev", os: "ubuntu"}
          - {name: "Python 3.11", python: "3.11-dev", os: "ubuntu"}
          - {name: "Python 3.12", python: "3.12-dev", os: "ubuntu"}
          - {name: "Python 3.13", python: "3.13-dev", os: "ubuntu"}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install qpdf ⚙️
        run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install qpdf
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools fpdf2 phonenumbers python-barcode pytest qrcode  pytest-cov click PyYAML
      - name: Test
        run: |
          pytest --cov=./brazilfiscalreport --cov-report=xml --cov-branch --doctest-glob="docs/*.md"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Engenere/BrazilFiscalReport
